name: gba

description: >
  Emulator components for the Gameboy Advance, written in cross-platform Dart.

homepage: https://github.com/matanlurey/gba.dart

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
  test_coverage: ^0.4.1
