# https://dart.dev/tools/pub/pubspec
name: gba

# Will be added only once published.
# description:
# homepage:
# repository:
# issue_tracker:
# documentation:

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  binary:
    git:
      url: git@github.com:matanlurey/binary.dart.git
      ref: 1.0.0
  meta:

dev_dependencies:
  pedantic:
  test:
